### ISSUE TITLE
Validating Form

### ISSUE THREAD

**Issue by stegel** [radiant/radiant-mailer-extension#1]
It appears that there is some form validation going on, but how do I display the error messages back to the user?

Thanks,

AJ

**Comment by saturnflyer** [comment]
The email list would be a good place to ask these questions. http://radiantcms.org/mailing-list/

The documentation should be updated, but you can find the tag for the error message here http://github.com/radiant/radiant-mailer-extension/blob/b661842349b8019d98aac9b50a576541d5f01d13/lib/mailer_tags.rb#L66
