### ISSUE TITLE
attribute name with html form element does not validate as strict XHTML

### ISSUE THREAD

**Issue by MichaelTorfs** [radiant/radiant-mailer-extension#3]
It's not a major issue, but you might want to know this:

Attribute "name" exists, but can not be used for this element.

<form action="/contact/" method="post" id="mailer" name="mailer[contact]">

You have used the attribute named above in your document, but the document type you are using does not support that attribute for this element. This error is often caused by incorrect use of the "Strict" document type with a document that uses frames (e.g. you must use the "Transitional" document type)

Solution is here: http://snippets.dzone.com/posts/show/4073
I took a look at the code, but for me (not a coder) it looked like the name attribute is used all over the code, so I decided to leave it to real coders ;)

**Comment by ghost** [comment]
`name` on `form` was ["included for backwards compatibility" in html 4.01](http://www.w3.org/TR/html401/interact/forms.html#adef-name-FORM) and merely [**deprecated** in xhtml 1.0](http://www.w3.org/TR/xhtml1/diffs.html#h-4.10) but was never eliminated nor forbidden. this just sounds like the w3c validator being stupid/useless again. you might want to try http://validator.nu/ for a modern conformance checking experience.

i guess someone might interpret "...in XHTML 1.0, the name attribute of [the form element] is formally deprecated, and will be removed in a subsequent version of XHTML" as meaning "get those `name` attributes out of here." except that the "subsequent version of XHTML" they meant was the soon to be defunct [xhtml2](http://www.w3.org/News/2009#item119) and the subsequent version of xhtml [looks like it intends to make `name` on `form` conformant once more](http://www.whatwg.org/specs/web-apps/current-work/multipage/forms.html#the-form-element).

hope that clears it up.
