### ISSUE TITLE
Showing multiple checkboxes

### ISSUE THREAD

**Issue by stegel** [radiant/radiant-mailer-extension#4]
If I have a checkbox in my form, how do I show all selected values?

using r:mailer:get name="pieces" only shows one value

is it the r:mailer:get_each name="pieces" tag? If so, what is the tag i use inside the loop to show the value?

Thanks,

**Comment by jomz** [comment]
you're probably not waiting for an answer anymore, but:
it does not make sense to have multiple checkboxes with the same name, that's the difference between a checkbox and a radio button..
